project_name: tara

env: 测试环境
tester_name: litao

# 域名1
host: https://sigvoid.hk
# 域名2，支持多个域名配置
app_host:

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
notification_type: 4
# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: False

# 数据库相关配置
mysql_db:
  # 数据库开关
  switch: False
  host:
  user: root
  password: '123456'
  port: 3306

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/


### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 重要的事情说三遍
email:
  send_user: #
  email_host: #
  # 自己到QQ邮箱中配置stamp_key
  stamp_key: #
  # 收件人改成自己的邮箱
  send_list: #

# 飞书通知
lark:
  webhook: https://open.feishu.cn/open-apis/bot/v2/hook/425d1b73-d6be-4aa3-80d5-2cb927016670



